### ISSUE TITLE
display in a popup when double clicking a word with a modifier key

### ISSUE THREAD

**Issue by attila-lendvai** [danial23/wiktionary-chrome-extension#2]
i want to get rid of anything google/fb/etc from my life, and i'm looking for a replacement for the [Google Dictionary extension](https://chrome.google.com/webstore/detail/google-dictionary-by-goog/mgijmajocgfcbeboacabfgobmjgjcoja) for chromium.

the feature i'm looking for: when SHIFT is pressed while double clicking a word, then a popup shows the english definition of the clicked word.

i know that it's not a trivial feature, but please consider adding it.

**Comment by danial23** [comment]
@attila-lendvai Check out [v0.2.0](https://github.com/danial23/wiktionary-chrome-extension/releases/tag/v0.2.0) .

You can toggle popup mode with Alt+W and then it works just like Google Dictionary.
